name: Build

on: [push, pull_request]


jobs:
  build_wheels:
    name: Build wheels on ubuntu-20.04
    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - run: |
          sudo apt install graphviz
          wget http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.8.1.tar.gz
          tar -xzvf openfst-1.8.1.tar.gz
          cd openfst-1.8.1/
          ./configure --enable-far=true
          make -j4
          sudo make install
          echo "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib" >> ~/.bashrc
          source ~/.bashrc

      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.11.1.post1
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl